SOURCE_CATALOG = "samples"
SOURCE_SCHEMA = "tpch"

BRONZE_SCHEMA = "bronze"
SILVER_SCHEMA = "silver"
GOLD_SCHEMA = "gold"

CUSTOMER_SOURCE = f"{SOURCE_CATALOG}.{SOURCE_SCHEMA}.customer"
ORDERS_SOURCE = f"{SOURCE_CATALOG}.{SOURCE_SCHEMA}.orders"
