SOURCE_CATALOG = "samples"
SOURCE_SCHEMA = "tpch"

TARGET_CATALOG = "workspace"

BRONZE_SCHEMA = "marketing_bronze"
SILVER_SCHEMA = "marketing_silver"
GOLD_SCHEMA = "marketing_gold"

CUSTOMER_SOURCE = f"{SOURCE_CATALOG}.{SOURCE_SCHEMA}.customer"
ORDERS_SOURCE = f"{SOURCE_CATALOG}.{SOURCE_SCHEMA}.orders"

CUSTOMER_BRONZE = f"{TARGET_CATALOG}.{BRONZE_SCHEMA}.customer"
ORDERS_BRONZE = f"{TARGET_CATALOG}.{BRONZE_SCHEMA}.orders"

CUSTOMER_SILVER = f"{TARGET_CATALOG}.{SILVER_SCHEMA}.customer"
ORDERS_SILVER = f"{TARGET_CATALOG}.{SILVER_SCHEMA}.orders"

CUSTOMER_GOLD = f"{TARGET_CATALOG}.{GOLD_SCHEMA}.customer_marketing"
RPR_GOLD = f"{TARGET_CATALOG}.{GOLD_SCHEMA}.repeat_purchase_rate_by_segment"
COHORT_RETENTION_GOLD = f"{TARGET_CATALOG}.{GOLD_SCHEMA}.cohort_retention_1996"
ACTIVATION_MONITORING_GOLD = f"{TARGET_CATALOG}.{GOLD_SCHEMA}.monitoring_activation_rate_by_segment"
NEW_CUSTOMERS_MONITORING_GOLD = f"{TARGET_CATALOG}.{GOLD_SCHEMA}.monitoring_new_customers_monthly"

# Gold reads Silver (medallion: Bronze → Silver → Gold).
CUSTOMER_GOLD_SOURCE = CUSTOMER_SILVER
ORDERS_GOLD_SOURCE = ORDERS_SILVER
